# Instructions


‚óè **Preprocess the dataset**

‚óã Clean (preprocess all ‚Äúodd‚Äù columns, and pre-process values)

‚óã Enrich (get data from grouping operations, maybe enrich in different ways üëÄ)

‚óè Perform EDA (exploratory data analysis) on the dataset

‚óã Generate visualizations

‚óã Share your insights and conclusions

‚óè Preferably use Python


**Open Questions (optional):**

‚óè Any conclusions based on the number of companies created by date, month, year etc?

‚óè Does the number of branches for a CNPJ provided on the dataset is equal to the actual
number produced by the dataset?

‚óè What about the business activities (CNAE)? What are the main types? Can they be
aggregated into fewer groups?

‚óè What are the differences between the cities / zip codes?

‚óè Is it possible to catch any spatial relationships? Which visualizations would be best in
this case?

‚óè If you were to make any model from the data, which one do you think makes sense?

# Importing libraries and reading data

In [1]:
#Imports 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
import pymysql
import pandas_profiling
import re
from datetime import datetime

In [2]:
df = pd.read_csv('../data/raw_data.csv')

/Users/santiagochiesa/.pyenv/versions/3.8.12/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
df.head()

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,city_code,zip_code,capital_social,size_company,juri_description,email_provider
0,4363642000106,4363642,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,4106902,80410200,0.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,NaN
1,17001584000465,17001584,FILIAL,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,20 de setembro de 2018,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 7, 'tot_branches': '4 branches'}",Curitiba - PR,4106902,80610905,100000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,HOTMAIL.COM
2,6931423000454,6931423,FILIAL,FONTANA COMERCIO DE JOIAS LTDA,NaN,30 de julho de 2014,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '4 branches'}",Curitiba - PR,4106902,81200240,10000.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,NaN
3,39842321000179,39842321,MATRIZ,ZAZULE ESTACAO CURITIBA LTDA,ZAZULE ESTACAO CURITIBA,19 de novembro de 2020,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '1 branches'}",Curitiba - PR,4106902,80230903,10000.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,ZAZULE.COM.BR
4,81671679000223,81671679,FILIAL,JOSE PELAYO SANCHEZ & CIA LTDA,PELAYO CASA,09 de outubro de 2013,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '2 branches'}",Londrina - PR,4113700,86020000,50000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,NaN

# Data cleaning

In [4]:
# Checking data types

df.dtypes

document_number                int64
cnpj_basico                    int64
establishment_type            object
razao_social                  object
nome_fantasia                 object
opening_date                  object
cnae                           int64
cnae_description              object
total_branches_and_socios     object
city_state                    object
city_code                      int64
zip_code                      object
capital_social               float64
size_company                  object
juri_description              object
email_provider                object
dtype: object

In [5]:
# Checking duplicates

df.duplicated().sum() / len(df)

0.0

In [6]:
# Checking nulls

df.isna().sum() / len(df)

document_number              0.000000
cnpj_basico                  0.000000
establishment_type           0.000000
razao_social                 0.000000
nome_fantasia                0.328898
opening_date                 0.000000
cnae                         0.000000
cnae_description             0.000000
total_branches_and_socios    0.000000
city_state                   0.000000
city_code                    0.000000
zip_code                     0.000000
capital_social               0.000000
size_company                 0.000000
juri_description             0.000000
email_provider               0.341263
dtype: float64

In [7]:
#Checking column values
for column in df.columns:
    print(df[column].value_counts().head(20))
    print(df[column].value_counts().tail(10))
    print()
    print()

4363642000106     1
38353734000127    1
19747444000113    1
40390008000126    1
40455467000140    1
32936513000103    1
32551625000138    1
31774522000174    1
32474742000145    1
40275830000146    1
41722445000162    1
42194867000175    1
35678579000120    1
21978902000177    1
37365409000111    1
41894040000101    1
31157942000101    1
29988808000100    1
20879673000170    1
29953048000104    1
Name: document_number, dtype: int64
32172944000132    1
35032781000180    1
19209988000121    1
2380579000190     1
6168511000101     1
25168658000138    1
7947121000194     1
27153062000190    1
17964993000114    1
81722795000143    1
Name: document_number, dtype: int64


15913061    370
77500049    156
78586674    100
75584110     88
2905110      86
78614278     85
2869763      73
75923185     66
88212113     61
11137051     60
2031555      60
82658840     58
33098658     57
10302127     57
751089       54
76189406     54
77856995     52
2834982      52
18192964     49
9248166      49
Name: cnpj_basico, dtype: int64
9425106     1
8766326     1
33115646    1
38444785    1
3882798     1
12903378    1
4751729     1
988143      1
3169386     1
81722795    1
Name: cnpj_basico, dtype: int64


MATRIZ    1232586
FILIAL      49953
Name: establishment_type, dtype: int64
MATRIZ    1232586
FILIAL      49953
Name: establishment_type, dtype: int64


LUCKNOW EMPREENDIMENTOS E PARTICIPACOES LTDA.                          370
MERCADOMOVEIS LTDA                                                     156
VIACAO GARCIA LTDA                                                     100
EXAL - ADMINISTRACAO DE RESTAURANTES EMPRESARIAIS E FACILITIES LTDA     88
GR SERVICOS E ALIMENTACAO LTDA.                                         86
COMERCIAL DE MOVEIS BRASILIA LTDA                                       85
HORFRAN - COMERCIAL ELETRO MOVEIS LTDA                                  73
VALDAR MOVEIS LTDA                                                      66
COMERCIO DE MEDICAMENTOS BRAIR LTDA                                     61
INTERBELLE COMERCIO DE PRODUTOS DE BELEZA LTDA                          60
APETIT SERVICOS DE ALIMENTACAO LTDA                                     60
LABORATORIO DE ANALISES CLINICAS DAS NACOES LTDA                        58
PROVAR NEGOCIOS DE VAREJO LTDA.                                         57
FARMACIA IRMAOS PAVESI LTDA.                                            57
COMERCIO DE MEDICAMENTOS MAEOKA LTDA.                                   54
CONDOR SUPER CENTER LTDA                                                54
I. RIEDI & CIA. LTDA.                                                   52
CIMOPAR MOVEIS LTDA- EM RECUPERACAO JUDICIAL                            52
DAK INCORPORACOES IMOBILIARIAS - EIRELI                                 49
PROSPERA CONSTRUTORA E INCORPORADORA LTDA                               49
Name: razao_social, dtype: int64
METALPONTO ESTAMPARIA E MONTAGENS LTDA                     1
JMR EMPORIO DOS COMPONENTES PARA ESQUADRIAS LTDA           1
TINTAS MEZZALIRA LTDA                                      1
COMERCIAL DE FERRAGENS AGRICOLA LTDA                       1
OURIBLOC COM. IND. DE MATERIAIS DE CONSTRUCAO LTDA         1
JS COMERCIAL DE FERRO E ACO LTDA                           1
FRANCO & FRANCO, COMERCIO DE LAMINADOS DE MADEIRA LTDA.    1
ROBERTO JOSE DRESCH & CIA LTDA                             1
VIA TRACTOR COMERCIO DE FERRAMENTAS E PECAS LTDA           1
F B C FABRICA BRASILEIRA DE CATALIZADORES LTDA             1
Name: razao_social, dtype: int64


BAR DOS AMIGOS                       172
****                                 157
******                               150
O BOTICARIO                          140
*****                                129
ODONTO EXCELLENCE                    121
CACAU SHOW                           120
.                                    111
ESPACO DA BELEZA                      90
***                                   89
*******                               80
DOCE SABOR                            76
********                              68
MOTORISTA                             67
MERCEARIA NOSSA SENHORA APARECIDA     65
CANTINHO DO LANCHE                    63
OLIVEIRA TRANSPORTES                  61
JR CONSTRUCOES                        61
OLIVEIRA                              60
SAO JOAO FARMACIAS                    60
Name: nome_fantasia, dtype: int64
POLIANE TILLER DE SOUZA     1
IMPACTO CONFECCAO           1
HUB STREET WEAR             1
ADRI&COSTURAS               1
FLOR CITRICA                1
Oficina de Costura          1
CLEO E CIA                  1
JANETE W. KERBER            1
REGINA MORAES               1
PROVEDOR CANDIAO SAT NET    1
Name: nome_fantasia, dtype: int64


27 de janeiro de 2021      1282
26 de janeiro de 2021      1274
03 de mar√ßo de 2020        1272
30 de janeiro de 2020      1259
29 de janeiro de 2020      1253
09 de fevereiro de 2021    1242
10 de fevereiro de 2021    1228
08 de fevereiro de 2021    1222
23 de fevereiro de 2021    1222
02 de fevereiro de 2021    1217
25 de janeiro de 2021      1217
01 de fevereiro de 2021    1212
07 de junho de 2021        1206
18 de janeiro de 2021      1195
18 de fevereiro de 2021    1187
28 de janeiro de 2021      1176
24 de fevereiro de 2021    1173
20 de janeiro de 2021      1164
28 de janeiro de 2020      1160
13 de janeiro de 2021      1156
Name: opening_date, dtype: int64
28 de dezembro de 1978     1
28 de dezembro de 1981     1
04 de julho de 1972        1
30 de maio de 1972         1
13 de mar√ßo de 1952        1
22 de novembro de 1969     1
26 de agosto de 1985       1
02 de julho de 1967        1
12 de janeiro de 1983      1
11 de fevereiro de 1969    1
Name: opening_date, dtype: int64


4781400    66146
9602501    47121
4399103    46573
7319002    33861
5611203    29552
4930202    28486
4712100    23139
5611201    20565
8219999    18033
9602502    17535
9700500    16579
4321500    16313
4930201    15869
4723700    15618
5620104    15506
4520001    14874
4530703    14207
4330404    14141
5229099    13978
1412601    12697
Name: cnae, dtype: int64
133405     1
312404     1
2449102    1
2092401    1
4940000    1
2652300    1
2442300    1
6450600    1
729401     1
2094100    1
Name: cnae, dtype: int64


Com√©rcio varejista de artigos do vestu√°rio e acess√≥rios                                                                         66146
Cabeleireiros, manicure e pedicure                                                                                              47121
Obras de alvenaria                                                                                                              46573
Promo√ß√£o de vendas                                                                                                              33861
Lanchonetes, casas de ch√°, de sucos e similares                                                                                 29552
Transporte rodovi√°rio de carga, exceto produtos perigosos e mudan√ßas, intermunicipal, interestadual e internacional             28486
Com√©rcio varejista de mercadorias em geral, com predomin√¢ncia de produtos aliment√≠cios - minimercados, mercearias e armaz√©ns    23139
Restaurantes e similares                                                                                                        20565
Prepara√ß√£o de documentos e servi√ßos especializados de apoio administrativo n√£o especificados anteriormente                      18033
Atividades de Est√©tica e outros servi√ßos de cuidados com a beleza                                                               17535
Servi√ßos dom√©sticos                                                                                                             16579
Instala√ß√£o e manuten√ß√£o el√©trica                                                                                                16313
Transporte rodovi√°rio de carga, exceto produtos perigosos e mudan√ßas, municipal                                                 15869
Com√©rcio varejista de bebidas                                                                                                   15618
Fornecimento de alimentos preparados preponderantemente para consumo domiciliar                                                 15506
Servi√ßos de manuten√ß√£o e repara√ß√£o mec√¢nica de ve√≠culos automotores                                                             14874
Com√©rcio a varejo de pe√ßas e acess√≥rios novos para ve√≠culos automotores                                                         14207
Servi√ßos de pintura de edif√≠cios em geral                                                                                       14141
Outras atividades auxiliares dos transportes terrestres n√£o especificadas anteriormente                                         13978
Confec√ß√£o de pe√ßas do vestu√°rio, exceto roupas √≠ntimas e as confeccionadas sob medida                                           12697
Name: cnae_description, dtype: int64
Metalurgia dos metais preciosos                                  1
Resseguros                                                       1
Sociedades de capitaliza√ß√£o                                      1
Fabrica√ß√£o de t√™nis de qualquer material                         1
Extra√ß√£o de min√©rios de ni√≥bio e tit√¢nio                         1
Cultivo de c√≠tricos, exceto laranja                              1
Fabrica√ß√£o de ado√ßantes naturais e artificiais                   1
Atividades associativas n√£o especificadas anteriormente          1
Fabrica√ß√£o de locomotivas, vag√µes e outros materiais rodantes    1
Fabrica√ß√£o de catalisadores                                      1
Name: cnae_description, dtype: int64


{'tot_socios': 1, 'tot_branches': '1 branches'}    946830
{'tot_socios': 2, 'tot_branches': '1 branches'}    202952
{'tot_socios': 3, 'tot_branches': '1 branches'}     24197
{'tot_socios': 2, 'tot_branches': '2 branches'}     20822
{'tot_socios': 1, 'tot_branches': '2 branches'}     19686
{'tot_socios': 4, 'tot_branches': '1 branches'}      8657
{'tot_socios': 2, 'tot_branches': '3 branches'}      6365
{'tot_socios': 1, 'tot_branches': '3 branches'}      5224
{'tot_socios': 3, 'tot_branches': '2 branches'}      3406
{'tot_socios': 5, 'tot_branches': '1 branches'}      3140
{'tot_socios': 2, 'tot_branches': '4 branches'}      3017
{'tot_socios': 1, 'tot_branches': '4 branches'}      2314
{'tot_socios': 2, 'tot_branches': '5 branches'}      1654
{'tot_socios': 4, 'tot_branches': '2 branches'}      1480
{'tot_socios': 3, 'tot_branches': '3 branches'}      1436
{'tot_socios': 6, 'tot_branches': '1 branches'}      1367
{'tot_socios': 1, 'tot_branches': '5 branches'}      1261
{'tot_socios': 2, 'tot_branches': '6 branches'}      1171
{'tot_socios': 1, 'tot_branches': '6 branches'}       822
{'tot_socios': 2, 'tot_branches': '7 branches'}       813
Name: total_branches_and_socios, dtype: int64

{'tot_socios': 19, 'tot_branches': '5 branches'}     1
{'tot_socios': 52, 'tot_branches': '2 branches'}     1
{'tot_socios': 14, 'tot_branches': '14 branches'}    1
{'tot_socios': 64, 'tot_branches': '3 branches'}     1
{'tot_socios': 61, 'tot_branches': '1 branches'}     1
{'tot_socios': 7, 'tot_branches': '41 branches'}     1
{'tot_socios': 5, 'tot_branches': '55 branches'}     1
{'tot_socios': 11, 'tot_branches': '59 branches'}    1
{'tot_socios': 51, 'tot_branches': '3 branches'}     1
{'tot_socios': 57, 'tot_branches': '1 branches'}     1
Name: total_branches_and_socios, dtype: int64


Curitiba - PR                305883
Londrina - PR                 71330
Maring√° - PR                  68031
Cascavel - PR                 40407
Ponta Grossa - PR             39580
S√£o Jos√© dos Pinhais - PR     38732
Foz do Igua√ßu - PR            33285
Colombo - PR                  25420
Pinhais - PR                  18644
Guarapuava - PR               17380
Toledo - PR                   17159
Arauc√°ria - PR                14634
Apucarana - PR                14465
Arapongas - PR                13859
Fazenda Rio Grande - PR       13516
Paranagu√° - PR                13424
Umuarama - PR                 12890
Campo Mour√£o - PR             12611
Campo Largo - PR              12266
Sarandi - PR                  11319
Name: city_state, dtype: int64
Diamante do Sul - PR         130
Iguatu - PR                  114
Porto Barreiro - PR          112
S√£o Manoel do Paran√° - PR    110
Santa In√™s - PR              106
Esperan√ßa Nova - PR           96
Jardim Olinda - PR            94
Mirador - PR                  91
Ariranha do Iva√≠ - PR         79
Nova Alian√ßa do Iva√≠ - PR     71
Name: city_state, dtype: int64


4106902    305883
4113700     71330
4115200     68031
4104808     40407
4119905     39580
4125506     38732
4108304     33285
4105805     25420
4119152     18644
4109401     17380
4127700     17159
4101804     14634
4101408     14465
4101507     13859
4107652     13516
4118204     13424
4128104     12890
4104303     12611
4104204     12266
4126256     11319
Name: city_code, dtype: int64
4107124    130
4110052    114
4120150    112
4125555    110
4123600    106
4107520     96
4112603     94
4115903     91
4101853     79
4116505     71
Name: city_code, dtype: int64


85960000    6031
85884000    4956
83260000    4707
86300000    4629
83430000    4599
86200000    4570
85660000    4421
86430000    4280
83750000    4270
86990000    4225
85950000    4086
83280000    4062
83255000    3859
87160000    3621
86360000    3561
85555000    3550
87140000    3546
86975000    3544
84500000    3539
86400000    3515
Name: zip_code, dtype: int64
83055470    1
85854210    1
85804080    1
85601118    1
87080360    1
87047405    1
81030320    1
80060200    1
85501292    1
87035065    1
Name: zip_code, dtype: int64


1000.0      163046
5000.0      148191
10000.0     130955
0.0         102376
1.0         101720
20000.0      67602
2000.0       53049
30000.0      41333
100000.0     38932
3000.0       38746
50000.0      35487
15000.0      31119
100.0        20649
500.0        20006
40000.0      15641
1500.0       11966
4000.0       11489
25000.0      11273
60000.0       9507
6000.0        9180
Name: capital_social, dtype: int64
1471794.0     1
2466000.0     1
440800.0      1
2276000.0     1
11078700.0    1
9382281.0     1
449588.0      1
797900.0      1
21430.0       1
842000.0      1
Name: capital_social, dtype: int64


NOT_INFORMED     1157465
OTHER              67281
SMALL_COMPANY      57793
Name: size_company, dtype: int64
NOT_INFORMED     1157465
OTHER              67281
SMALL_COMPANY      57793
Name: size_company, dtype: int64


Empres√°rio (Individual)                                                     830328
Sociedade Empres√°ria Limitada                                               371126
Empresa Individual de Responsabilidade Limitada (de Natureza Empres√°ria)     69592
Sociedade Simples Limitada                                                   11493
Name: juri_description, dtype: int64
Empres√°rio (Individual)                                                     830328
Sociedade Empres√°ria Limitada                                               371126
Empresa Individual de Responsabilidade Limitada (de Natureza Empres√°ria)     69592
Sociedade Simples Limitada                                                   11493
Name: juri_description, dtype: int64


GMAIL.COM              253330
HOTMAIL.COM            158192
hotmail.com             87612
gmail.com               80548
OUTLOOK.COM             18210
YAHOO.COM.BR            16042
yahoo.com.br            10752
outlook.com              6328
UOL.COM.BR               5837
BOL.COM.BR               4954
uol.com.br               4702
bol.com.br               4145
TERRA.COM.BR             3612
terra.com.br             3601
CONTABILIZEI.COM.BR      3293
brturbo.com.br           2995
LIVE.COM                 2664
YAHOO.COM                2498
BRTURBO.COM.BR           2224
ICLOUD.COM               2176
Name: email_provider, dtype: int64
larossi.com.be                1
LUVICONTABIL.COM.BR           1
SITIODOCAQUI.COM.BR           1
USOAR.ES                      1
LIPEGABI.COM.BR               1
KRZAK.COM.BR                  1
ZAZULE.COM.BR                 1
CHACARAMINASDAGUA.COM.BR      1
FIUZASISTEMASESITES.COM.BR    1
EDUEVENTOS.COM.BR             1
Name: email_provider, dtype: int64

**Preoprocesing To Do**

document_number: OK.

cnpj_basico: some do not have 8 numbers, should extract from document number.

establishment_type: OK.

razao_social: Some LTDA have dots, other doesn't. Otherwise OK.

nome_fantasia: * and dots might be missing data. 32% nulls. Caps are not consistent.

opening_date: Date is expressed as string.

cnae: OK, probably can be grouped differently.

cnae_description: OK, probably can be grouped differently.

total_branches_and_socios: JSON-Like. tot_socios and tot_branches should be different columns. Only numbers should be extracted.

city_state: OK.

city_code: OK.

zip_code: OK.

capital_social: some 0s and 1s that do not make much sense.

size_company: OK.

juri_description: OK.

email_provider: Caps and names are not consistent, can be grouped better.

In [8]:
# Correcting cnpj_basico column with the first 8 digits of the document_number

df['cnpj_basico'] = df.document_number.apply(lambda x: int(str(x)[0:8]))

In [9]:
df['cnpj_basico'].value_counts()

15913061    370
77500049    156
78586674    100
75584110     88
78614278     85
           ...
36808588      1
10423294      1
12369448      1
25307438      1
81722795      1
Name: cnpj_basico, Length: 1238260, dtype: int64

In [10]:
# Replacing nulls

df.nome_fantasia.fillna('Missing_Name', inplace=True)
df.email_provider.fillna('Missing_Email', inplace=True)

In [11]:
# Replacing nome_fantasia with odd values

df.loc[df.nome_fantasia=='.', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='***', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='****', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='*****', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='******', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='*******', 'nome_fantasia'] = 'Missing_Name'
df.loc[df.nome_fantasia=='********', 'nome_fantasia'] = 'Missing_Name'

In [12]:
# Modifying dates

# Extracting year
df.opening_date[0]

# Extracting day 

# Extracting month

# Replacing month by number with dictionary (?)

'29 de mar√ßo de 2001'

In [13]:
# Extracting date year
df['opening_year'] = df.opening_date.apply(lambda x: x[-4:])

In [14]:
# Extracting date day
df['opening_day'] = df.opening_date.apply(lambda x: x[0:2])

In [15]:
# Extracting date month
df['opening_month']= df.opening_date.apply(lambda x: "".join(re.findall("[a-zA-Z]+", x)).strip('de'))

In [16]:
# Creating month names list
month_names = list(df.opening_month.value_counts().index)

In [17]:
# Creating month numbers list
month_numbers= ['03', '05', '02', '01', '04', '08', '06', '07', '10', '09', '11', '12']

In [18]:
# Creating function to replace values
def replacer(to_replace, list_1, list_2):
    for i in range(len(list_1)):
        if to_replace == list_1[i]:
            to_replace = list_2[i]
    return to_replace

In [19]:
# Testing function
foo = 'julho'
replacer(foo, month_names, month_numbers)

'07'

In [20]:
# Replacing month names for numbers
df['opening_month'] = df.opening_month.apply(lambda x: replacer(x, month_names, month_numbers))

In [21]:
df['opening_month_year'] = df.opening_month + '-' + df.opening_year

In [22]:
# Creating clean date column
df['opening_date_clean'] = df.opening_year + '/' + df.opening_month + '/' + df.opening_day

In [23]:
# Changing to date time format
df['opening_date_clean'] = df['opening_date_clean'].apply(lambda x: datetime.strptime(x, '%Y/%m/%d'))

In [24]:
df

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,zip_code,capital_social,size_company,juri_description,email_provider,opening_year,opening_day,opening_month,opening_month_year,opening_date_clean
0,4363642000106,43636420,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,...,80410200,0.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,2001,29,03,03-2001,2001-03-29
1,17001584000465,17001584,FILIAL,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,20 de setembro de 2018,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 7, 'tot_branches': '4 branches'}",Curitiba - PR,...,80610905,100000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,HOTMAIL.COM,2018,20,09,09-2018,2018-09-20
2,6931423000454,69314230,FILIAL,FONTANA COMERCIO DE JOIAS LTDA,Missing_Name,30 de julho de 2014,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '4 branches'}",Curitiba - PR,...,81200240,10000.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,2014,30,07,07-2014,2014-07-30
3,39842321000179,39842321,MATRIZ,ZAZULE ESTACAO CURITIBA LTDA,ZAZULE ESTACAO CURITIBA,19 de novembro de 2020,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '1 branches'}",Curitiba - PR,...,80230903,10000.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,ZAZULE.COM.BR,2020,19,11,11-2020,2020-11-19
4,81671679000223,81671679,FILIAL,JOSE PELAYO SANCHEZ & CIA LTDA,PELAYO CASA,09 de outubro de 2013,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '2 branches'}",Londrina - PR,...,86020000,50000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,Missing_Email,2013,09,10,10-2013,2013-10-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282534,3535330000250,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,27 de julho de 2011,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,83420000,12437843.0,OTHER,Sociedade Empres√°ria Limitada,Missing_Email,2011,27,07,07-2011,2011-07-27
1282535,3535330000412,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,31 de julho de 2019,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,83420000,12437843.0,OTHER,Sociedade Empres√°ria Limitada,AEQAEROESPACIAL.COM.BR,2019,31,07,07-2019,2019-07-31
1282536,4186294000149,41862940,MATRIZ,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,12 de dezembro de 2000,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Lapa - PR,...,83750000,550000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2000,12,12,12-2000,2000-12-12
1282537,4186294000220,41862940,FILIAL,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,13 de setembro de 2016,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Campo Largo - PR,...,83604365,550000.0,SMALL_COMPANY,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2016,13,09,09-2016,2016-09-13
1282538,81722795000143,81722795,MATRIZ,F B C FABRICA BRASILEIRA DE CATALIZADORES LTDA,Missing_Name,10 de janeiro de 1990,2094100,Fabrica√ß√£o de catalisadores,"{'tot_socios': 4, 'tot_branches': '1 branches'}",Contenda - PR,...,83730000,0.0,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,1990,10,01,01-1990,1990-01-10

In [25]:
# Creating total socios and total branches columns

df['total_socios'] = df.total_branches_and_socios.apply(lambda x: re.findall(r'\d+', x)[0])

df['total_branches'] = df.total_branches_and_socios.apply(lambda x: re.findall(r'\d+', x)[1])

In [26]:
# Transforming total socios and total branches type to int

df['total_socios'] = df.total_socios.apply(lambda x: int(x))
df['total_branches'] = df.total_branches.apply(lambda x: int(x))

In [27]:
df

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,size_company,juri_description,email_provider,opening_year,opening_day,opening_month,opening_month_year,opening_date_clean,total_socios,total_branches
0,4363642000106,43636420,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,...,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,2001,29,03,03-2001,2001-03-29,6,1
1,17001584000465,17001584,FILIAL,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,20 de setembro de 2018,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 7, 'tot_branches': '4 branches'}",Curitiba - PR,...,SMALL_COMPANY,Sociedade Empres√°ria Limitada,HOTMAIL.COM,2018,20,09,09-2018,2018-09-20,7,4
2,6931423000454,69314230,FILIAL,FONTANA COMERCIO DE JOIAS LTDA,Missing_Name,30 de julho de 2014,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '4 branches'}",Curitiba - PR,...,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,2014,30,07,07-2014,2014-07-30,5,4
3,39842321000179,39842321,MATRIZ,ZAZULE ESTACAO CURITIBA LTDA,ZAZULE ESTACAO CURITIBA,19 de novembro de 2020,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '1 branches'}",Curitiba - PR,...,NOT_INFORMED,Sociedade Empres√°ria Limitada,ZAZULE.COM.BR,2020,19,11,11-2020,2020-11-19,5,1
4,81671679000223,81671679,FILIAL,JOSE PELAYO SANCHEZ & CIA LTDA,PELAYO CASA,09 de outubro de 2013,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '2 branches'}",Londrina - PR,...,SMALL_COMPANY,Sociedade Empres√°ria Limitada,Missing_Email,2013,09,10,10-2013,2013-10-09,5,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282534,3535330000250,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,27 de julho de 2011,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,OTHER,Sociedade Empres√°ria Limitada,Missing_Email,2011,27,07,07-2011,2011-07-27,3,4
1282535,3535330000412,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,31 de julho de 2019,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,OTHER,Sociedade Empres√°ria Limitada,AEQAEROESPACIAL.COM.BR,2019,31,07,07-2019,2019-07-31,3,4
1282536,4186294000149,41862940,MATRIZ,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,12 de dezembro de 2000,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Lapa - PR,...,SMALL_COMPANY,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2000,12,12,12-2000,2000-12-12,3,2
1282537,4186294000220,41862940,FILIAL,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,13 de setembro de 2016,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Campo Largo - PR,...,SMALL_COMPANY,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2016,13,09,09-2016,2016-09-13,3,2
1282538,81722795000143,81722795,MATRIZ,F B C FABRICA BRASILEIRA DE CATALIZADORES LTDA,Missing_Name,10 de janeiro de 1990,2094100,Fabrica√ß√£o de catalisadores,"{'tot_socios': 4, 'tot_branches': '1 branches'}",Contenda - PR,...,NOT_INFORMED,Sociedade Empres√°ria Limitada,Missing_Email,1990,10,01,01-1990,1990-01-10,4,1

In [28]:
# Uppercasing email provider's column
df.email_provider = df.email_provider.apply(lambda x: x.upper())

In [29]:
# Creating a new column only with the email provider's company nam

df['email_provider_company'] = df.email_provider.apply(lambda x: x.split('.')[0])

In [30]:
df

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,juri_description,email_provider,opening_year,opening_day,opening_month,opening_month_year,opening_date_clean,total_socios,total_branches,email_provider_company
0,4363642000106,43636420,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,2001,29,03,03-2001,2001-03-29,6,1,MISSING_EMAIL
1,17001584000465,17001584,FILIAL,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,20 de setembro de 2018,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 7, 'tot_branches': '4 branches'}",Curitiba - PR,...,Sociedade Empres√°ria Limitada,HOTMAIL.COM,2018,20,09,09-2018,2018-09-20,7,4,HOTMAIL
2,6931423000454,69314230,FILIAL,FONTANA COMERCIO DE JOIAS LTDA,Missing_Name,30 de julho de 2014,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '4 branches'}",Curitiba - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,2014,30,07,07-2014,2014-07-30,5,4,MISSING_EMAIL
3,39842321000179,39842321,MATRIZ,ZAZULE ESTACAO CURITIBA LTDA,ZAZULE ESTACAO CURITIBA,19 de novembro de 2020,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '1 branches'}",Curitiba - PR,...,Sociedade Empres√°ria Limitada,ZAZULE.COM.BR,2020,19,11,11-2020,2020-11-19,5,1,ZAZULE
4,81671679000223,81671679,FILIAL,JOSE PELAYO SANCHEZ & CIA LTDA,PELAYO CASA,09 de outubro de 2013,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '2 branches'}",Londrina - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,2013,09,10,10-2013,2013-10-09,5,2,MISSING_EMAIL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282534,3535330000250,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,27 de julho de 2011,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,2011,27,07,07-2011,2011-07-27,3,4,MISSING_EMAIL
1282535,3535330000412,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,31 de julho de 2019,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,Sociedade Empres√°ria Limitada,AEQAEROESPACIAL.COM.BR,2019,31,07,07-2019,2019-07-31,3,4,AEQAEROESPACIAL
1282536,4186294000149,41862940,MATRIZ,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,12 de dezembro de 2000,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Lapa - PR,...,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2000,12,12,12-2000,2000-12-12,3,2,CWIAGRO
1282537,4186294000220,41862940,FILIAL,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,13 de setembro de 2016,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Campo Largo - PR,...,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2016,13,09,09-2016,2016-09-13,3,2,CWIAGRO
1282538,81722795000143,81722795,MATRIZ,F B C FABRICA BRASILEIRA DE CATALIZADORES LTDA,Missing_Name,10 de janeiro de 1990,2094100,Fabrica√ß√£o de catalisadores,"{'tot_socios': 4, 'tot_branches': '1 branches'}",Contenda - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,1990,10,01,01-1990,1990-01-10,4,1,MISSING_EMAIL

# Data Enrichment

In [31]:
# Economic activity grouping

df.cnae.value_counts().tail(20)

6530800    1
1532700    1
8425600    1
322102     1
1072402    1
2449103    1
1012104    1
5231103    1
722702     1
4751200    1
133405     1
312404     1
2449102    1
2092401    1
4940000    1
2652300    1
2442300    1
6450600    1
729401     1
2094100    1
Name: cnae, dtype: int64

In [32]:
df.loc[df.cnae==729401]

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,juri_description,email_provider,opening_year,opening_day,opening_month,opening_month_year,opening_date_clean,total_socios,total_branches,email_provider_company
1282482,75704213000365,75704213,FILIAL,PLUMBUM COMERCIO E REPRESENTACOES DE PRODUTOS ...,Missing_Name,20 de setembro de 1989,729401,Extra√ß√£o de min√©rios de ni√≥bio e tit√¢nio,"{'tot_socios': 2, 'tot_branches': '9 branches'}",Adrian√≥polis - PR,...,Sociedade Empres√°ria Limitada,MISSING_EMAIL,1989,20,09,09-1989,1989-09-20,2,9,MISSING_EMAIL

In [33]:
len(df.cnae.unique())

1222

In [34]:
df.cnae.nunique()

1222

In [35]:
df.cnae_description.nunique()

1221

In [36]:
# Importing CNAE detailed category data
# Source: https://www.ibge.gov.br/estatisticas/metodos-e-classificacoes/classificacoes-e-listas-estatisticas/9078-classificacao-nacional-de-atividades-economicas.html?=&t=resultados
cnae_df = pd.read_excel('../data/cnae_detail.xls')

In [37]:
# Renaming columns
cnae_df.columns=['cnae_section', 'cnae_division', 'cnae_group', 'cnae_class', 'cnae_subclass', 'denomination']

In [38]:
# Keeping only numerical values fore numerical code groupings:
for col in cnae_df.columns[1:-1]:    
    cnae_df[col] = cnae_df[col].apply(lambda x: "".join(re.findall(r'\d+', str(x))))

In [39]:
cnae_df

,cnae_section,cnae_division,cnae_group,cnae_class,cnae_subclass,denomination
0,NaN,,,,,NaN
1,NaN,,,,,(continua)
2,Se√ß√£o,,,,,Denomina√ß√£o
3,A,,,,,"AGRICULTURA, PECU√ÅRIA, PRODU√á√ÉO FLORESTAL, PES..."
4,NaN,01,,,,"AGRICULTURA, PECU√ÅRIA E SERVI√áOS RELACIONADOS"
...,...,...,...,...,...,...
2704,U,,,,,ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUI√á√ïE...
2705,NaN,99,,,,ORGANISMOS INTERNACIONAIS E OUTRAS INSTITUI√á√ïE...
2706,NaN,,990,,,Organismos internacionais e outras institui√ß√µe...
2707,NaN,,,99008,,Organismos internacionais e outras institui√ß√µe...
2708,NaN,,,,9900800,Organismos internacionais e outras institui√ß√µe...

In [40]:
# Examining observation with 6 digit CENAE
df.loc[df.cnae==133411]

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,juri_description,email_provider,opening_year,opening_day,opening_month,opening_month_year,opening_date_clean,total_socios,total_branches,email_provider_company
1282536,4186294000149,41862940,MATRIZ,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,12 de dezembro de 2000,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Lapa - PR,...,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2000,12,12,12-2000,2000-12-12,3,2,CWIAGRO
1282537,4186294000220,41862940,FILIAL,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,13 de setembro de 2016,133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Campo Largo - PR,...,Sociedade Empres√°ria Limitada,CWIAGRO.COM.BR,2016,13,09,09-2016,2016-09-13,3,2,CWIAGRO

In [41]:
# Checking value in CNAE dataframe
cnae_df.loc[cnae_df.denomination == 'Cultivo de p√™ssego']

,cnae_section,cnae_division,cnae_group,cnae_class,cnae_subclass,denomination
63,NaN,,,,0133411,Cultivo de p√™ssego

In [42]:
# Transforming CNAE to string
df.cnae = df.cnae.apply(lambda x: str(x))
# Creating a column to flag 6 digits CNAE
df['foo'] = df.cnae.apply(lambda x: len(x))

In [43]:
# Checking results
df.foo.value_counts()

7    1270816
6      11723
Name: foo, dtype: int64

In [44]:
# Adding a 0 at the begining of 6 digit CNAEs
df.loc[df.foo==6, 'cnae'] = '0'+ df.cnae

In [45]:
# Checking results
df['foo'] = df.cnae.apply(lambda x: len(x))
df.foo.value_counts()

7    1282539
Name: foo, dtype: int64

In [46]:
# Dropping temporal column
df.drop(columns='foo', inplace=True)

In [47]:
# Creating CNAE division, group and class columns
df['cnae_division'] = df.cnae.apply(lambda x: x[0:2])
df['cnae_group'] = df.cnae.apply(lambda x: x[0:3])
df['cnae_class'] = df.cnae.apply(lambda x: x[0:5])

In [48]:
# Creating dictionary mapping CNAE sections to divisions
cnae_section_division = {'A': ['01', '02', '03'], 
                         'B': ['05', '06', '07', '08', '09'], 
                         'C':list(range(10, 34)), 
                         'D':[35], 
                         'E':list(range(36,40)), 
                         'F':list(range(41,44)), 
                         'G':list(range(45,48)), 
                         'H':list(range(49,54)), 
                         'I':list(range(55,57)), 
                         'J':list(range(58,64)), 
                         'K':list(range(64,67)), 
                         'L':[68], 
                         'M':list(range(69, 76)), 
                         'N':list(range(77, 83)), 
                         'O':[84], 
                         'P':[85],
                         'Q':list(range(86,89)),
                         'R': list(range(90,94)), 
                         'S':list(range(94,97)), 
                         'T':[97], 
                         'U':[99]}

In [49]:
# Transforming dictionary values from int to strings
for i in cnae_section_division:
    for j in range(len(cnae_section_division[i])):
        cnae_section_division[i][j] = str(cnae_section_division[i][j])

In [50]:
# Defining function for using the dictionary to map our dataframe's cnae_division to secitons
def dict_imputer(to_check, dictionary):
    for i in dictionary:
        if to_check in dictionary[i]:
            return i

In [51]:
# Creating our CNAE section column, using the dictionary and function defined above
df['cnae_section'] = df.cnae_division.apply(lambda x: dict_imputer(x, cnae_section_division))

In [52]:
# Checking nulls

df.isna().sum() / len(df)

document_number              0.0
cnpj_basico                  0.0
establishment_type           0.0
razao_social                 0.0
nome_fantasia                0.0
opening_date                 0.0
cnae                         0.0
cnae_description             0.0
total_branches_and_socios    0.0
city_state                   0.0
city_code                    0.0
zip_code                     0.0
capital_social               0.0
size_company                 0.0
juri_description             0.0
email_provider               0.0
opening_year                 0.0
opening_day                  0.0
opening_month                0.0
opening_month_year           0.0
opening_date_clean           0.0
total_socios                 0.0
total_branches               0.0
email_provider_company       0.0
cnae_division                0.0
cnae_group                   0.0
cnae_class                   0.0
cnae_section                 0.0
dtype: float64

In [53]:
# Merging dataframes to obtain CNAE descriptions for every CNAE grouping
for col in cnae_df.columns[0:-2]:
    foo_df = pd.DataFrame(cnae_df[[col, 'denomination']])
    df= df.merge(foo_df, how='left', on= col)
    df.rename(columns={'denomination': col + '_description'}, inplace=True)

In [54]:
df

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,total_branches,email_provider_company,cnae_division,cnae_group,cnae_class,cnae_section,cnae_section_description,cnae_division_description,cnae_group_description,cnae_class_description
0,4363642000106,43636420,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,...,1,MISSING_EMAIL,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...
1,17001584000465,17001584,FILIAL,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,FAGE COMERCIO VAREJISTA DE BIJUTERIAS LTDA,20 de setembro de 2018,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 7, 'tot_branches': '4 branches'}",Curitiba - PR,...,4,HOTMAIL,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...
2,6931423000454,69314230,FILIAL,FONTANA COMERCIO DE JOIAS LTDA,Missing_Name,30 de julho de 2014,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '4 branches'}",Curitiba - PR,...,4,MISSING_EMAIL,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...
3,39842321000179,39842321,MATRIZ,ZAZULE ESTACAO CURITIBA LTDA,ZAZULE ESTACAO CURITIBA,19 de novembro de 2020,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '1 branches'}",Curitiba - PR,...,1,ZAZULE,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...
4,81671679000223,81671679,FILIAL,JOSE PELAYO SANCHEZ & CIA LTDA,PELAYO CASA,09 de outubro de 2013,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 5, 'tot_branches': '2 branches'}",Londrina - PR,...,2,MISSING_EMAIL,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1282534,3535330000250,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,27 de julho de 2011,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,4,MISSING_EMAIL,25,255,25501,C,IND√öSTRIAS DE TRANSFORMA√á√ÉO,"FABRICA√á√ÉO DE PRODUTOS DE METAL, EXCETO M√ÅQUIN...","Fabrica√ß√£o de equipamento b√©lico pesado, armas...","Fabrica√ß√£o de equipamento b√©lico pesado, armas..."
1282535,3535330000412,35353300,FILIAL,AEQ ALIANCA ELETROQUIMICA LTDA,Missing_Name,31 de julho de 2019,2550101,"Fabrica√ß√£o de equipamento b√©lico pesado, excet...","{'tot_socios': 3, 'tot_branches': '4 branches'}",Quatro Barras - PR,...,4,AEQAEROESPACIAL,25,255,25501,C,IND√öSTRIAS DE TRANSFORMA√á√ÉO,"FABRICA√á√ÉO DE PRODUTOS DE METAL, EXCETO M√ÅQUIN...","Fabrica√ß√£o de equipamento b√©lico pesado, armas...","Fabrica√ß√£o de equipamento b√©lico pesado, armas..."
1282536,4186294000149,41862940,MATRIZ,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,12 de dezembro de 2000,0133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Lapa - PR,...,2,CWIAGRO,01,013,01334,A,"AGRICULTURA, PECU√ÅRIA, PRODU√á√ÉO FLORESTAL, PES...","AGRICULTURA, PECU√ÅRIA E SERVI√áOS RELACIONADOS",Produ√ß√£o de lavouras permanentes,"Cultivo de frutas de lavoura permanente, excet..."
1282537,4186294000220,41862940,FILIAL,CWI AGRO FRUTICOLA LTDA,CWI AGRO & FRUTI,13 de setembro de 2016,0133411,Cultivo de p√™ssego,"{'tot_socios': 3, 'tot_branches': '2 branches'}",Campo Largo - PR,...,2,CWIAGRO,01,013,01334,A,"AGRICULTURA, PECU√ÅRIA, PRODU√á√ÉO FLORESTAL, PES...","AGRICULTURA, PECU√ÅRIA E SERVI√áOS RELACIONADOS",Produ√ß√£o de lavouras permanentes,"Cultivo de frutas de lavoura permanente, excet..."
1282538,81722795000143,81722795,MATRIZ,F B C FABRICA BRASILEIRA DE CATALIZADORES LTDA,Missing_Name,10 de janeiro de 1990,2094100,Fabrica√ß√£o de catalisadores,"{'tot_socios': 4, 'tot_branches': '1 branches'}",Contenda - PR,...,1,MISSING_EMAIL,20,209,20941,C,IND√öSTRIAS DE TRANSFORMA√á√ÉO,FABRICA√á√ÉO DE PRODUTOS QU√çMICOS,Fabrica√ß√£o de produtos e preparados qu√≠micos d...,Fabrica√ß√£o de catalisadores

In [55]:
# Checking nulls

df.isna().sum() / len(df)

document_number              0.0
cnpj_basico                  0.0
establishment_type           0.0
razao_social                 0.0
nome_fantasia                0.0
opening_date                 0.0
cnae                         0.0
cnae_description             0.0
total_branches_and_socios    0.0
city_state                   0.0
city_code                    0.0
zip_code                     0.0
capital_social               0.0
size_company                 0.0
juri_description             0.0
email_provider               0.0
opening_year                 0.0
opening_day                  0.0
opening_month                0.0
opening_month_year           0.0
opening_date_clean           0.0
total_socios                 0.0
total_branches               0.0
email_provider_company       0.0
cnae_division                0.0
cnae_group                   0.0
cnae_class                   0.0
cnae_section                 0.0
cnae_section_description     0.0
cnae_division_description    0.0
cnae_group_description       0.0
cnae_class_description       0.0
dtype: float64

In [56]:
# Grouping by month-year

# Grouping by economic activity

# Grouping by zip_code or city

# Grouping by capital levels

# Grouping by cnpj b√°sico (Company)

# Adding economic data (Actividad Econ√≥mica, Consumo, Precios Commodities: Azucar, Soja, Maiz, Trigo, Cafe)

In [57]:
# Indicators

# Openings per month, social activity, zipcode or city

# Capital per month, avg capital per company

# Average socios, branches per company

# Big companies openings over total openings

In [58]:
df.columns

Index(['document_number', 'cnpj_basico', 'establishment_type', 'razao_social',
       'nome_fantasia', 'opening_date', 'cnae', 'cnae_description',
       'total_branches_and_socios', 'city_state', 'city_code', 'zip_code',
       'capital_social', 'size_company', 'juri_description', 'email_provider',
       'opening_year', 'opening_day', 'opening_month', 'opening_month_year',
       'opening_date_clean', 'total_socios', 'total_branches',
       'email_provider_company', 'cnae_division', 'cnae_group', 'cnae_class',
       'cnae_section', 'cnae_section_description', 'cnae_division_description',
       'cnae_group_description', 'cnae_class_description'],
      dtype='object')

In [59]:
df.head(1)

,document_number,cnpj_basico,establishment_type,razao_social,nome_fantasia,opening_date,cnae,cnae_description,total_branches_and_socios,city_state,...,total_branches,email_provider_company,cnae_division,cnae_group,cnae_class,cnae_section,cnae_section_description,cnae_division_description,cnae_group_description,cnae_class_description
0,4363642000106,43636420,MATRIZ,TRES GERACOES EM MODA LTDA,TRES GERACOES,29 de mar√ßo de 2001,4789001,"Com√©rcio varejista de suvenires, bijuterias e ...","{'tot_socios': 6, 'tot_branches': '1 branches'}",Curitiba - PR,...,1,MISSING_EMAIL,47,478,47890,G,COM√âRCIO; REPARA√á√ÉO DE VE√çCULOS AUTOMOTORES E ...,COM√âRCIO VAREJISTA,Com√©rcio varejista de produtos novos n√£o espec...,Com√©rcio varejista de outros produtos novos n√£...

In [60]:
df_grouped_time = df.groupby([df.opening_month_year]).agg({'capital_social': ['count', 'mean', 'median', 'min', 'max'], 
                                                           'total_socios': ['mean'],
                                                           'total_branches': ['mean']})

In [61]:
df_grouped_time.columns = ['openings', 
                            'capital_social_mean',
                            'capital_social_median',
                            'capital_social_min', 
                            'capital_social_max',
                            'total_socios_mean',
                            'total_branches_mean']

In [62]:
df_grouped_time.tail(50)

,openings,capital_social_mean,capital_social_median,capital_social_min,capital_social_max,total_socios_mean,total_branches_mean
opening_month_year,,,,,,,
12-1971,47,2.044034e+06,50000.00,0.0,2.783298e+07,3.106383,2.765957
12-1972,55,9.613471e+04,0.00,0.0,1.452434e+06,2.600000,2.290909
12-1973,78,4.910145e+05,0.00,0.0,2.177400e+07,2.192308,2.012821
12-1974,62,2.605745e+06,3500.00,0.0,6.873710e+07,2.064516,2.774194
12-1975,69,3.474459e+05,1.22,0.0,5.002000e+06,2.318841,2.623188
12-1976,61,2.108932e+07,0.00,0.0,1.277226e+09,2.262295,1.704918
12-1977,78,1.085618e+06,0.00,0.0,3.000000e+07,2.038462,2.294872
12-1978,94,2.062346e+05,0.00,0.0,1.000000e+07,2.436170,1.446809
12-1979,85,2.291495e+06,4000.00,0.0,1.438570e+08,2.482353,2.800000
12-1980,123,8.176477e+06,0.00,0.0,9.771027e+08,1.894309,3.186992
12-1981,137,8.031912e+05,0.00,0.0,2.987164e+07,1.992701,7.678832
12-1982,160,3.795539e+05,0.00,0.0,3.182715e+07,1.981250,2.125000
12-1983,165,5.464948e+06,0.00,0.0,8.238755e+08,1.963636,2.436364
12-1984,145,2.978055e+05,0.00,0.0,2.000000e+07,1.882759,2.358621
12-1985,259,3.168223e+05,0.00,0.0,3.400000e+07,1.806950,1.660232
12-1986,310,4.666032e+06,0.00,0.0,1.142612e+09,1.725806,2.161290
12-1987,267,7.503080e+06,0.00,0.0,1.803425e+09,1.925094,9.033708
12-1988,282,2.513911e+05,0.00,0.0,1.877971e+07,1.829787,1.943262
12-1989,309,1.688925e+06,0.00,0.0,1.183113e+08,1.864078,2.919094
12-1990,270,3.855315e+05,0.00,0.0,1.630000e+07,1.718519,3.255556
12-1991,217,6.862119e+05,0.00,0.0,6.774249e+07,1.718894,1.566820
12-1992,346,2.103475e+06,0.00,0.0,6.722510e+08,1.786127,1.832370
12-1993,499,2.485531e+06,0.00,0.0,6.330048e+08,1.729459,2.575150
12-1994,593,5.607512e+05,0.00,0.0,1.882689e+08,1.672850,1.817875
12-1995,441,1.349586e+06,0.00,0.0,2.349000e+08,1.680272,2.070295
12-1996,447,3.443591e+05,0.00,0.0,4.600000e+07,1.836689,1.653244
12-1997,521,2.933147e+05,0.00,0.0,3.704671e+07,1.813820,1.587332
12-1998,648,1.090846e+06,0.00,0.0,1.015672e+08,1.939815,2.023148
12-1999,713,1.564300e+06,1000.00,0.0,5.964150e+08,1.875175,2.893408
12-2000,662,1.000269e+07,4000.50,0.0,5.958189e+09,1.812689,3.433535
12-2001,660,3.925820e+05,0.00,0.0,7.522561e+07,1.816667,1.925758
12-2002,731,8.125200e+05,3000.00,0.0,1.024753e+08,1.906977,1.943912
12-2003,754,2.387474e+06,2000.00,0.0,8.597100e+08,1.903183,2.075597
12-2004,886,4.544961e+05,2000.00,0.0,1.318560e+08,1.731377,5.970655
12-2005,918,4.152980e+05,20000.00,0.0,5.000000e+07,1.764706,2.135076
12-2006,880,7.755138e+05,20000.00,0.0,3.511053e+08,1.844318,1.592045
12-2007,1072,4.029157e+05,20000.00,0.0,6.000000e+07,1.763993,1.868470
12-2008,1202,8.916214e+05,20000.00,0.0,2.451280e+08,1.759567,1.613977
12-2009,1535,8.402189e+06,15000.00,0.0,5.958189e+09,1.619544,4.390228
12-2010,2020,4.160320e+06,15000.00,0.0,5.958189e+09,1.595050,2.550000
12-2011,2055,6.610489e+05,10000.00,0.0,1.923581e+08,1.531873,2.373236
12-2012,2211,1.159083e+06,15000.00,0.0,6.388838e+08,1.523293,3.294437
12-2013,2428,3.124897e+06,10000.00,0.0,3.393813e+09,1.561779,25.771417
12-2014,2557,3.801069e+05,10000.00,0.0,1.100000e+08,1.434885,1.752444
12-2015,3107,5.395613e+06,10000.00,0.0,1.487470e+10,1.399421,3.703251
12-2016,3720,7.669674e+05,10000.00,0.0,1.216761e+09,1.326613,2.228226
12-2017,4456,2.506300e+05,5000.00,0.0,1.923581e+08,1.296005,1.292639
12-2018,6379,6.083642e+05,5000.00,0.0,1.510396e+09,1.254115,1.877724
12-2019,10795,7.868564e+05,4000.00,0.0,1.308491e+09,1.185086,2.317369
12-2020,13654,1.213400e+06,4000.00,0.0,5.394486e+09,1.161857,1.442801